### ISSUE TITLE
Email Only Contact?

### ISSUE THREAD

**Issue by MACscr** [christiaan/zohocrmclient#17]
Is it possible to add a contact as just an email address? When I look at the API docs, it looks like the only requirement for a contact is a Last Name, but I could be wrong.

**Comment by runemoennike** [comment]
It depends on your settings in Zoho. If a field is required in those settings, it must be present when creating a record from the API as well. Some fields seem to be required because they're used for duplicate checking. See this list of which field is used for each module: https://www.zoho.eu/crm/help/api/insertrecords.html#Duplicate_Check_Fields

**Comment by christiaan** [comment]
Closing this issue as Zoho now has an official PHP SDK on composer see https://packagist.org/packages/zohocrm/php-sdk-archive
