### ISSUE TITLE
uploadFile Method not working

### ISSUE THREAD

**Issue by aarryy** [christiaan/zohocrmclient#9]
Trying to upload an attachment to a zoho account. I created my own UploadFile request and passed $id and $content into the class and it returned error 4424, saying that "Unable to process your request. Please verify whether you have provided proper file." I can achieve the job using php sample code that comes with zoho api. The cause is http_build_query function called in BuzzTransport class. It encodes "@" character in $content variable into %40 so the zoho server won't be able to tell it's a file upload. Wonder if there's clean way to suppress http_build_query from being called. Thanks in advance!

**Comment by christiaan** [comment]
First to clear things up, http_build_query has nothing to do with this. The file upload convention with the @ sign is specific for curl see [CURLOPT_POSTFIELDS](http://php.net/curl_setopt).

That being said, for all currently implemented API calls file uploads have not been needed yet. Implementing support for file uploads can be done easily by updating the BuzzTransport. Using $this->browser->submit() instead of the ->post() method and a way to know which params to turn into FileUpload instances.

**Comment by yousuvic** [comment]
hi,

I have the same problem, did you found the solution pls ?

Thank you

**Comment by christiaan** [comment]
Closing this issue as Zoho now has an official PHP SDK on composer see https://packagist.org/packages/zohocrm/php-sdk-archive
